// <auto-generated />
namespace projectPart3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_KHACH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_KHACH));
        
        string IMigrationMetadata.Id
        {
            get { return "202012110810259_update_KHACH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
