// <auto-generated />
namespace projectPart3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
<<<<<<< HEAD:projectPart3/projectPart3/Migrations/202012141256378_addnew.Designer.cs
    public sealed partial class addnew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnew));
        
        string IMigrationMetadata.Id
        {
            get { return "202012141256378_addnew"; }
=======
    public sealed partial class editorderdetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editorderdetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202012150535220_edit order-detail"; }
>>>>>>> ba6980ea3110cb240cf276a15f6ad2018f92e418:projectPart3/projectPart3/Migrations/202012150535220_edit order-detail.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
